/* AUTO-GENERATED by scripts/create-stripe-payment-links.mjs — do not edit by hand.
   TEST mode links, generated 2026-08-11T16:14:33.441Z.
   Maps variant id (js/products.js) -> Stripe Payment Link URL.
   Re-run the script to add new variants. Safe to commit (public URLs). */
window.PAYMENT_LINKS = {
  "retatrutide-10mg-1": "https://buy.stripe.com/test_9B6dR2bcM5ui1ngeFhgIo00",
  "retatrutide-10mg": "https://buy.stripe.com/test_4gMcMY6WwaOCd5Y8gTgIo01",
  "retatrutide-24mg-1": "https://buy.stripe.com/test_5kQ4gs80A9Ky6HAap1gIo02",
  "retatrutide-24mg": "https://buy.stripe.com/test_5kQ4gs0y86ymea22WzgIo03",
  "retatrutide-48mg-1": "https://buy.stripe.com/test_bJebIUeoY1e2fe668LgIo04",
  "retatrutide-48mg": "https://buy.stripe.com/test_28E00ccgQaOCea2eFhgIo05",
  "bac-water-10ml": "https://buy.stripe.com/test_dRm14g94Ee0O0jc0OrgIo06",
  "bac-water-30ml": "https://buy.stripe.com/test_dRm4gsgx69Ky1ng7cPgIo07",
  "bac-water-30ml-3": "https://buy.stripe.com/test_cNieV6a8Ig8W6HAfJlgIo08",
  "bac-water-30ml-5": "https://buy.stripe.com/test_9B66oAbcMcWK9TM9kXgIo09",
  "insulin-syr-31g-10": "https://buy.stripe.com/test_aFabIU2Gg09Yc1UeFhgIo0a",
  "insulin-syr-31g-50": "https://buy.stripe.com/test_dRm00c3KkaOC8PIdBdgIo0b",
  "insulin-syr-31g-100": "https://buy.stripe.com/test_dRmeV6gx64qeea254HgIo0c",
  "insulin-syr-31g-300": "https://buy.stripe.com/test_4gM9AM2Gg7Cqgiaap1gIo0d"
};
