/* ============================================================================
   PRODUCT CATALOG — the three cards on the page, in order.

   Each product: id, name, tagline (the "for the …" line), copy (the
   rat-effect paragraph), variants. Each VARIANT is a separately purchasable
   amount with its own Stripe Payment Link:
     { id, label, price, buyUrl? }
   The link for a variant comes from window.PAYMENT_LINKS[variant.id]
   (generated by scripts/create-stripe-payment-links.mjs), or a manual
   `buyUrl` set here as an override.

   Copy is final per the build brief — effect sentences stay about THE RAT.
   No dosing, timeframes, percentages, or human-use claims.
   ========================================================================== */
window.PRODUCTS = [
  {
    id: "retatrutide",
    name: "Retatrutide",
    tagline: "for the rounder rat",
    copy: "Your rat will experience a sudden and dignified loss of interest in the snack corner. Appetite: reduced. Waistline: also reduced. In rodent research, this triple-agonist (GLP-1/GIP/glucagon) is the headline compound for metabolic and body-composition studies. Your rat has never looked better, and your rat knows it.",
    variants: [
      { id: "retatrutide-10mg", label: "10mg (10 vials/kit)", price: 268 },
      { id: "retatrutide-24mg", label: "24mg (10 vials/kit)", price: 498 },
      { id: "retatrutide-48mg", label: "48mg (10 vials/kit)", price: 828 }
    ]
  },
  {
    id: "bac-water",
    name: "Bacteriostatic Water",
    tagline: "the unsung hero",
    copy: "Peptides arrive freeze-dried, as a powder. This sterile water is what turns the powder back into something a laboratory can actually use. Your rat cannot do anything with powder. Every kit on this page needs this. Buy it with the peptides; thank us later.",
    variants: [
      { id: "bac-water-30ml", label: "30mL (0.9% benzyl alcohol)", price: 18 }
    ]
  },
  {
    id: "insulin-syr",
    name: "Insulin Syringes",
    tagline: "for measuring tiny things precisely",
    copy: "Sterile, single-use, and very thin, because the entire job is measuring very small amounts very accurately. A laboratory essential. Your rat will barely look up from his wheel.",
    variants: [
      { id: "insulin-syr-31g-100", label: "31G 0.5mL, 100-pack", price: 24 }
    ]
  }
];
