/* ============================================================================
   SITE CONFIG — single source of truth for branding & site-wide settings.
   To rebrand, edit the values here; the page, age gate, and disclaimers all
   read from this object.
   ========================================================================== */
window.SITE = {
  brand: "DEFINITELY FOR RATS",
  legalName: "Definitely For Rats",

  // Compliance disclaimer — shown under the hero, in the footer, and in the
  // age gate. Load-bearing: do not shorten, collapse, or hide it.
  disclaimer:
    "Products are sold for laboratory research use only and are not for " +
    "human consumption. Effects described refer to laboratory rodent " +
    "research. They are definitely for rats.",

  ageGate: 21,                         // minimum age (years)
  currencySymbol: "$",

  // Payments: per-variant Stripe Payment Links, generated by
  // scripts/create-stripe-payment-links.mjs into js/payment-links.js.
  // NEVER put a Stripe secret key (sk_...) in this file — it ships to the
  // browser. Only public buy.stripe.com URLs belong on the client.
  payment: {
    provider: "stripe",
    currency: "usd",

    // Multi-item checkout — ONE payment for the whole cart. When set, the cart
    // POSTs here and gets back a Stripe Checkout Session URL. Deploy
    // /api/create-checkout-session.js (included) to a host that runs functions
    // — Vercel or Netlify — and set STRIPE_SECRET_KEY in that host's
    // environment. The secret key NEVER goes in this repo.
    //   e.g. "/api/create-checkout-session"
    //
    // GitHub Pages cannot run functions, so leave this empty when deploying
    // there. The cart then falls back to the per-variant hosted Payment Links
    // in js/payment-links.js, which pay one product at a time.
    checkoutEndpoint: "/api/create-checkout-session"
  }
};
